# This is a basic workflow to help you get started with Actions

name: A3

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'adapter.h'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'adapter.h'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ./assignment

      - name: Checkout Tester
        uses: actions/checkout@v2
        with:
          repository: seneca-btp600-w23/testers
          token: ${{ secrets.TESTER_ACCESS }}
          path: ./tester

      - name: Copy cpp tester files
        run: cp ./tester/a3main.cpp ./

      - name: Copy linkedlist answers files
        run: cp ./tester/linkedlist.cpp ./

      - name: Copy linkedlist answers files
        run: cp ./tester/linkedlist.h ./

      - name: Copy assignment files
        run: cp ./assignment/adapter.h ./

      # Runs a single command using the runners shell
      - name: Compile
        run: c++ linkedlist.cpp a3main.cpp -std=c++0x -o checklab

      # Runs a set of commands using the runners shell
      - name: Run
        run: timeout 120 ./checklab
 
