# This is a basic workflow to help you get started with Actions

name: A5

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - 'a5.h'
      - 'a5.cpp'
      
  pull_request:
    branches: [ main ]
    paths:
      - 'a5.h'
      - 'a5.cpp'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          path: ./assignment

      - name: Checkout Tester
        uses: actions/checkout@v2
        with:
          repository: seneca-btp600-w23/testers
          token: ${{ secrets.TESTER_ACCESS }}
          path: ./tester

      - name: Copy cpp tester files
        run: cp ./tester/samefile.cpp ./

      - name: Copy cpp tester files
        run: cp ./tester/a5tester.cpp ./

      - name: Copy cpp tester files
        run: cp ./tester/a5correct.txt ./

      - name: Copy assignment files
        run: cp ./assignment/a5.h ./

      - name: Copy assignment files
        run: cp ./assignment/a5.cpp ./

      # Runs a single command using the runners shell
      - name: Compile
        run: c++ a5tester.cpp a5.cpp -std=c++0x -o a5

      # Runs a single command using the runners shell
      - name: Compile2
        run: c++ samefile.cpp -std=c++0x -o checklab

      # Runs a set of commands using the runners shell
      - name: Get Output
        run: timeout 200 ./a5 > a5output.txt

      - name: Check Output file
        run: cat ./a5output.txt      
      

      # Runs a set of commands using the runners shell
      - name: Check Output
        run: timeout 120 ./checklab a5output.txt a5correct.txt

 
